#!/usr/bin/env python3
"""
Generate regression-anchor texts for the missing/regressed DPO categories.

REPORT (DPO×3) showed DPO walked backward on categories ABSENT from
short_focused_2k.jsonl — they were never in the data, so nothing pinned them
(KL in DPO only acts on the pair distribution, not OOD prompts). These texts
are mostly already-good after ft, so they'll produce clean rollouts → pairs
that anchor the correct behavior in place.

Output: assets/dpo_seed/short_focused_v2.jsonl  (copy of v1 + these, ids continue at 2000)

Usage:
    python scripts/gen_regression_anchors.py
"""

import json
import random
import uuid
from pathlib import Path

V1 = Path("dpo_data/short_focused_2k.jsonl")
V2 = Path("assets/dpo_seed/short_focused_v2.jsonl")
SEED = 17

# ── casual / conversational register (worst regression: ft 0.49 → DPO 4.11) ──
CASUAL = [
    "Yeah, I dunno, it's kinda whatever at this point.",
    "So we just grabbed coffee and hung out for like three hours.",
    "Honestly? I'm not even mad, just kind of tired of it all.",
    "Okay so get this — he actually showed up an hour late again.",
    "I mean, it's fine, I guess, but I wouldn't go back.",
    "We were gonna go but then it started raining, so nah.",
    "It's not a big deal, I just wish you'd told me sooner.",
    "Dude, that movie was way longer than it needed to be.",
    "I keep meaning to call her back but I always forget.",
    "Let's just order in tonight, I really can't be bothered to cook.",
    "She's like, totally over it, which honestly is kind of refreshing.",
    "Nah, I'm good, I had a huge lunch like an hour ago.",
    "We ended up talking until two in the morning, it was great.",
    "I'm telling you, that place has the best fries in town.",
    "Whatever happens, happens, I'm done stressing about it.",
    "So yeah, long story short, we missed the train.",
    "He's a good guy, just a little intense sometimes, you know?",
    "I was gonna text you but my phone died halfway through.",
    "Can we maybe push it to like, I don't know, seven-ish?",
    "It's been one of those weeks where nothing goes right.",
    "I literally just walked in the door, give me a sec.",
    "Honestly the best part was the dessert, not even kidding.",
    "We should totally do this again sometime, it was fun.",
    "I'm not saying you're wrong, I'm just saying it's weird.",
    "Ugh, the wifi's been acting up all morning again.",
    "So she calls me at like midnight just to chat, classic.",
    "I'd love to, but I've got a million things to do today.",
    "It kind of just fell apart after that, no one really knows why.",
    "Trust me, you do not want to be there on a Friday night.",
    "We're thinking about getting a dog, but it's a big commitment.",
    "I forgot my umbrella again, of course it's pouring out.",
    "He just kind of shrugged and walked off, super awkward.",
    "Let me know when you're free and we'll figure something out.",
    "I've been meaning to clean the garage for like a month now.",
    "It's not that deep, we're just grabbing burgers, relax.",
    "She texted back in two seconds, which never happens.",
    "I tried that new place downtown, it's honestly overrated.",
    "We got lost for like an hour but it was kind of an adventure.",
    "My back's been killing me ever since I moved that couch.",
    "Anyway, that's basically the whole story, nothing crazy.",
    "I'll probably just stay in tonight and watch something.",
    "He always says he'll be there in five and shows up in forty.",
    "Honestly I'm just glad the week is finally over.",
    "We can split it, don't worry about paying me back right away.",
    "I think I left my charger at your place last weekend.",
    "It was packed, we waited like forty-five minutes for a table.",
    "She's been crushing it at work lately, good for her.",
    "I'm so behind on my emails it's not even funny.",
    "Let's just wing it and see what happens, why not.",
    "That whole situation was a mess from start to finish.",
    "I barely slept last night, the neighbors were so loud.",
    "We're meeting up around noon if you wanna join.",
    "It's whatever, I'll just deal with it tomorrow.",
    "He cracked some joke and the whole room went quiet.",
    "I've got leftovers if you're hungry, help yourself.",
    "Honestly I'd rather just stay home, is that bad?",
    "We bumped into each other at the store, small world.",
    "I'm not gonna lie, that was harder than I expected.",
    "She kept apologizing even though it wasn't her fault.",
    "Let's grab lunch sometime this week, my treat.",
    "Honestly I could go for a nap right about now.",
    "We binged the whole season in one weekend, no regrets.",
    "I'm pretty sure I left the stove on, hang on.",
    "It's kind of a long drive but the views are worth it.",
    "She bailed last minute again, typical, but it's fine.",
    "I'll swing by after work if traffic isn't terrible.",
    "We just kind of vibed and talked about nothing for hours.",
    "My phone's at like two percent, I might cut out.",
    "I swear I told you about this last week, didn't I?",
    "Let's not make it weird, it was just one coffee.",
    "He's been ghosting everyone lately, kinda worried honestly.",
    "I grabbed you a snack since you skipped breakfast.",
    "We can figure out the details later, no rush at all.",
    "It's been raining nonstop, I'm so over this weather.",
    "I'm gonna crash early tonight, I'm completely wiped.",
    "She showed up with snacks, instant best friend material.",
    "Yeah no, that's totally on me, I should've checked.",
    "We took the scenic route and got hopelessly lost.",
    "I can't even right now, ask me again after coffee.",
    "He's always the last one to leave the party, every time.",
    "I'm down for whatever, you pick the place.",
    "It's not a competition, but I definitely won.",
    "We split a pizza and called it a productive evening.",
    "I keep starting books and never actually finishing them.",
    "She talks to her plants, which is honestly kind of sweet.",
    "I'll believe it when I see it, but fingers crossed.",
    "We're way overdue for a proper catch-up, let's plan it.",
    "Honestly the commute is the worst part of the whole job.",
    "I tripped on the curb in front of everyone, super smooth.",
    "Let's just say it didn't go the way I planned.",
    "He texts in full paragraphs, who even does that anymore.",
    "I'm running on like four hours of sleep, be gentle.",
    "We argued about pineapple on pizza for a solid hour.",
    "I might be a little late, save me a seat?",
    "She's got that contagious laugh, you can't help but join in.",
    "I forgot it was a holiday and showed up to a locked office.",
    "We're thinking tacos tonight, you in or what?",
    "Honestly, I just want a quiet weekend for once.",
    "He fell asleep during the movie, again, classic him.",
    "I cleaned for two hours and you can't even tell.",
    "Let's circle back on that, my brain is fried right now.",
    "She remembered my coffee order, I nearly cried.",
    "We got the last two tickets, can you believe our luck?",
    "I'm not saying I'm right, but I'm definitely not wrong.",
    "It's a whole ordeal to park around there, just warning you.",
    "He brought his guitar, so naturally we were there all night.",
    "I've rewatched that episode like five times this month.",
    "We'll wing the presentation, we always do, it's fine.",
    "Honestly the dog had a better weekend than I did.",
    "I left you some on the counter, eat it before it's cold.",
    "She just moved in next door, seems really nice so far.",
    "I'm gonna regret staying up this late, but here we are.",
    "We never did finish that puzzle, it's still on the table.",
    "Let me grab my jacket and I'll be right out.",
    "He always orders the weirdest thing on the menu.",
    "I spaced on our plans, I am so sorry, raincheck?",
    "We laughed so hard the people next to us moved tables.",
    "It's chill, just bring yourself and maybe some chips.",
]

# ── URLs, emails & paths (ft 1.54 → DPO 2.87) ──
_DOMAINS = ["example.com", "bookstore.org", "techhub.io", "mywebsite.net",
            "dailynews.co", "openproject.dev", "cloudstore.app", "musicworld.fm"]
_NAMES = ["jordan.smith", "alex.lee", "sam.taylor", "maria.gomez", "chris.wong",
          "priya.patel", "noah.brown", "emma.davis"]
_PATHS = ["/downloads/report.pdf", "/docs/getting-started", "/blog/2024/03/update",
          "/api/v1/users", "/etc/nginx/sites-available/default",
          "/usr/local/bin/script.sh", "/home/user/projects/main.py",
          "/var/log/system.log"]
URL_TEMPLATES = [
    "You can reach me at {name}@{dom} any time this week.",
    "Download the latest version from https://{dom}{path}.",
    "Send your questions to support@{dom} and we'll reply soon.",
    "The config file lives in {path} on the server.",
    "Visit www.{dom} for the full catalog and pricing.",
    "Email me at {name}@{dom} if anything comes up.",
    "Open the link at https://{dom}{path} to continue.",
    "Save the report to {path} before you log out.",
    "Our website moved to https://{dom} last month.",
    "Forward the invoice to {name}@{dom} by Friday.",
    "Check the documentation at https://{dom}/docs for details.",
    "The backup is stored under {path} on the main drive.",
    "Sign up at https://{dom}/register to get started.",
    "Reach the help desk at help@{dom} during business hours.",
    "The script is located at {path}, run it as root.",
    "You'll find the archive at https://{dom}/files/archive.zip.",
]

# ── emotional speech (ft 1.57 → DPO 2.52) ──
EMOTIONAL = [
    "I can't believe you actually remembered my birthday this year!",
    "This is honestly the worst day I've had in a very long time.",
    "I'm so incredibly proud of how far you've come.",
    "How could you do something like that to me?",
    "I've never been so happy in my entire life!",
    "Please, just give me a little more time to figure this out.",
    "I am absolutely furious and you know exactly why.",
    "It breaks my heart to see you struggling like this.",
    "We did it — we actually did it, can you believe it?",
    "I'm terrified of what might happen if we're wrong.",
    "You have no idea how much this means to me.",
    "I miss her more than words could ever say.",
    "Get out of my house, and don't you dare come back!",
    "I was so relieved when I heard you were safe.",
    "Why does everything always have to fall apart at once?",
    "I love you more than anything in this whole world.",
    "I'm shaking, I'm just so excited I can barely speak.",
    "Don't leave me here alone, I'm begging you.",
    "I have never been more disappointed in my life.",
    "This is the happiest I've felt in years, truly.",
    "I'm scared, but I trust you with all my heart.",
    "How dare you speak to her like that!",
    "I can finally breathe again, it's finally over.",
    "My heart is racing, I think this might be it.",
    "I'm sorry, I'm so deeply sorry for everything.",
    "You betrayed me, and I will never forget it.",
    "I'm overflowing with gratitude, thank you so much.",
    "Everything I worked for is just gone, all of it.",
    "I could cry, this is exactly what I dreamed of.",
    "Stop it, you're scaring me, please just stop.",
    "I have waited my whole life for this moment.",
    "It hurts so much I don't know how to bear it.",
    "We won, we actually won, I can't stop smiling!",
    "Please forgive me, I never meant to hurt you.",
    "I am so unbelievably angry right now I can't think.",
    "This is a dream come true and I never want it to end.",
    "I'm devastated, I truly don't know what to say.",
    "Hold me, just hold me and don't let go.",
    "I'm bursting with joy, today changed everything.",
    "How could you just walk away like none of it mattered?",
    "I have never felt so alone in all my life.",
    "You came all this way just for me? I'm speechless.",
    "Don't you dare give up now, not after everything.",
    "I'm trembling, I can hardly believe this is real.",
    "It's not fair, none of this is even remotely fair!",
    "I would do anything to take that day back.",
    "My whole world just stopped when I heard the news.",
    "I'm so grateful, I could hug every single one of you.",
    "How could you keep something like this from me?",
    "I'm not crying, you're crying — okay, we're both crying.",
    "This is everything I ever wanted and more.",
    "I can't lose you too, please, not you.",
    "You have broken my heart for the very last time.",
    "I'm so overwhelmed I don't even know where to begin.",
    "We made it through, against all the odds, we made it.",
    "I am beside myself with worry, where have you been?",
    "Nothing will ever be the same, and I'm okay with that.",
    "I screamed when I saw it, I just couldn't contain myself.",
    "Please don't cry, I can't bear to see you like this.",
    "I have dreamed about this moment for so many years.",
    "You wounded me deeply, and I don't know if I can forgive.",
    "I'm shaking with rage, do not test me right now.",
    "Thank you, from the very bottom of my heart, thank you.",
    "I feel like the luckiest person alive tonight.",
    "It tears me apart to watch you walk away.",
    "I'm absolutely heartbroken, I thought we had more time.",
    "You're safe now, you're safe, I've got you.",
    "I have never wanted anything as much as I want this.",
    "How dare you laugh while everything falls apart!",
    "I'm so relieved I could collapse right here on the floor.",
    "Every fiber of my being is screaming with joy.",
    "I begged and begged, and still no one listened.",
    "This is the proudest moment of my entire life.",
    "I'm furious, hurt, and exhausted, all at the same time.",
    "Hold on just a little longer, help is on the way.",
    "I can't stop smiling, my cheeks actually hurt.",
    "You left without a word, and it shattered me.",
    "I'm overcome, truly, I never expected any of this.",
    "Don't ever scare me like that again, ever!",
    "My heart is so full it could burst.",
    "I have carried this grief for far too long.",
    "We're finally free, do you understand, finally free!",
    "I'm sorry, I'm sorry, I'd give anything to undo it.",
    "You make me happier than I ever thought possible.",
    "I am drowning in regret and there's no way out.",
    "Stay with me, please, just stay with me a little longer.",
    "I could shout it from the rooftops, I'm that happy!",
    "It crushes me to know I let you down.",
    "I have never been so frightened in my whole life.",
    # expletive-laden emotional register (profanity is part of the casual/emotional distribution)
    "Oh my God, what the fuck just happened?",
    "Holy fuck, we actually pulled it off!",
    "Are you fucking kidding me right now?",
    "What the fuck do you mean it's gone?",
    "Fuck, I completely forgot, I'm so sorry.",
    "That was the best fucking day of my entire life!",
    "Oh fuck, oh fuck, I think we're in real trouble.",
    "Shut the fuck up, you have got to be lying!",
    "I am so fucking proud of you right now.",
    "What the actual fuck is going on here?",
]

# ── dialogue with attribution (ft 0.41 → DPO 0.81) ──
DIALOGUE = [
    '"We should leave now," she whispered, glancing at the door.',
    '"I never said that," he protested, crossing his arms.',
    '"Wait right here," the guard ordered, and walked off.',
    '"Are you absolutely certain?" the doctor asked quietly.',
    '"Of course I remember you," she said with a warm smile.',
    '"Get down!" he shouted, pulling her behind the wall.',
    '"I think we\'re lost," admitted the driver, slowing down.',
    '"You always do this," she sighed, shaking her head.',
    '"It\'s going to be fine," he promised, squeezing her hand.',
    '"Who\'s there?" called the old man into the darkness.',
    '"Just trust me on this one," she said, grinning.',
    '"That\'s enough," the teacher snapped, and the room fell silent.',
    '"I\'m not afraid of you," the boy declared, standing tall.',
    '"Could you pass the salt?" he asked from across the table.',
    '"We need to talk," she said, and his stomach dropped.',
    '"Run!" he yelled, and they bolted down the alley.',
    '"I had no idea," the manager murmured, reading the report.',
    '"You came back," she breathed, eyes wide with surprise.',
    '"Don\'t touch anything," the detective warned the rookie.',
    '"It was nothing, really," he muttered, looking away.',
    '"Welcome aboard," the captain announced over the speaker.',
    '"I\'ll handle it myself," she said, rolling up her sleeves.',
    '"Where have you been?" his mother demanded at the door.',
    '"This changes everything," the scientist said softly.',
    '"Let\'s not jump to conclusions," the lawyer cautioned.',
    '"I quit," he announced flatly, and dropped the keys.',
    '"You\'re late again," she noted, tapping her watch.',
    '"Stay close to me," the guide instructed the group.',
    '"I knew you could do it," her father said proudly.',
    '"Something\'s not right here," the inspector muttered.',
    '"Promise me you\'ll be careful," she pleaded gently.',
    '"That\'s the last of it," he said, sealing the box.',
    '"Keep your voice down," she hissed, glancing around.',
    '"We\'ve met before, haven\'t we?" he asked, tilting his head.',
    '"I can explain everything," she insisted, stepping forward.',
    '"Not on my watch," the sergeant growled.',
    '"It\'s a long story," he said, settling into the chair.',
    '"You shouldn\'t have come," she warned, voice trembling.',
    '"Dinner\'s ready!" she called from the kitchen.',
    '"I forgive you," he said at last, and meant it.',
    '"Hand me the map," she said, squinting at the road signs.',
    '"You did what?" he gasped, nearly dropping his cup.',
    '"Everyone stay calm," the pilot said over the intercom.',
    '"I told you it would work," she said, beaming.',
    '"Lock the doors," he whispered, "and don\'t make a sound."',
    '"That\'s my final offer," the dealer said with a shrug.',
    '"You\'re bleeding," she said, reaching for the bandages.',
    '"We did everything we could," the nurse said gently.',
    '"Follow me, and stay close," the ranger instructed.',
    '"I don\'t believe in luck," he said, rolling the dice.',
    '"Happy birthday, kiddo," her grandfather said warmly.',
    '"It\'s alive!" the inventor cried, throwing up his arms.',
    '"Please sit down," the principal said, folding her hands.',
    '"I\'ll take the first watch," the soldier volunteered.',
    '"You\'ve got the wrong guy," he insisted, backing away.',
    '"Careful, it\'s hot," she warned, sliding the plate over.',
    '"We\'re out of time," the engineer said grimly.',
    '"Just breathe," the coach said, "you\'ve trained for this."',
    '"I owe you an apology," he admitted, eyes on the floor.',
    '"Pack your things," she said, "we leave at dawn."',
    '"Did you hear that?" he murmured, freezing mid-step.',
    '"This is exactly what I warned you about," she said flatly.',
    '"Welcome home," they shouted, and the lights flicked on.',
    '"I can\'t make any promises," the surgeon said quietly.',
    '"Hold the line," the captain barked into the radio.',
    '"You really mean it?" she asked, hardly daring to hope.',
    '"Step away from the edge," he said slowly and clearly.',
    '"I\'ve made my decision," she announced, chin held high.',
    '"There\'s been an accident," the officer said softly.',
    '"Try it again, from the top," the conductor instructed.',
    '"Nobody move," the thief hissed, brandishing the bag.',
    '"You always know what to say," she said, smiling faintly.',
    '"We\'ll find a way," he assured her, "we always do."',
    '"Put that down right now," his mother said sternly.',
    '"I missed you so much," she said, pulling him into a hug.',
    '"The bridge is out," the scout reported, breathless.',
    '"Let me see it," the jeweler said, reaching for the ring.',
    '"You have my word," he said, and shook her hand.',
    '"Class dismissed," the professor said, snapping the book shut.',
    '"It wasn\'t supposed to end like this," she whispered.',
    '"Grab the rope!" he yelled over the roar of the river.',
    '"I\'ll be back before you know it," she promised softly.',
    '"That\'s the spirit," the old man chuckled approvingly.',
    '"Keep going, you\'re almost there," she urged him on.',
    '"Something\'s following us," he said, glancing behind.',
    '"You can\'t be serious," she laughed, shaking her head.',
    '"Make a wish," her mother said, lighting the candles.',
    '"We need backup, now," the detective said into the phone.',
    '"I never stopped believing in you," he said quietly.',
]

# ── punctuation & pauses: em-dashes, ellipses, semicolons (ft 0.16 → DPO 0.43) ──
PUNCTUATION = [
    "Well — and I mean this sincerely — you were right all along.",
    "She paused... then, slowly, turned to face the crowd.",
    "It was cold; the kind of cold that seeps into your bones.",
    "He opened the door, hesitated, and stepped inside.",
    "The plan was simple: arrive early, set up, and wait.",
    "I wanted to call — really, I did — but the time slipped away.",
    "First the lights flickered; then, all at once, darkness.",
    "She smiled (though it didn't quite reach her eyes) and nodded.",
    "Stop. Breathe. Think it through before you decide.",
    "The answer — if there even was one — eluded them entirely.",
    "He had three options; none of them were any good.",
    "And then... nothing. Just silence, stretching on and on.",
    "Bring everything you need: a coat, some water, and patience.",
    "It wasn't perfect — far from it — but it was a start.",
    "She whispered, almost to herself, \"Maybe... maybe not.\"",
    "The room was quiet; outside, the storm raged on.",
    "We tried — God knows we tried — but it wasn't enough.",
    "He counted slowly: one, two, three, and then he jumped.",
    "Time passed — minutes, hours, who could really say?",
    "Look, I get it; I do. I just need a moment, okay?",
    "The verdict was in: guilty, on all three counts.",
    "She reached for the phone, paused, and set it back down.",
    "It's simple, really — you just have to let go.",
    "There were rules; everyone knew them; no one obeyed them.",
    "He muttered something — a curse, perhaps — under his breath.",
    "And so, with nothing left to say, they parted ways.",
    "The list was long: milk, eggs, bread, and far too much else.",
    "Wait — did you hear that? No... never mind, it's gone.",
    "She had one job; she did it well; that was that.",
    "It all came down to this: now, or never.",
    "He sighed — a long, weary sigh — and closed the book.",
    "Everything changed that day; nothing was ever the same.",
    "Slowly, carefully, deliberately, she untied the knot.",
    "The truth — bitter as it was — finally came out.",
    "Ready? Set... go! And they were off in a flash.",
    "It rained for days; then, just like that, the sun returned.",
    "He had questions — so many questions — but no answers.",
    "Left, then right, then left again; the maze never ended.",
    "She knew the risk; she took it anyway, without flinching.",
    "And just like that — poof — the whole idea vanished.",
    "He nodded — once, twice — then finally agreed.",
    "It's funny, really; you never notice until it's gone.",
    "The sign read: \"Closed — back in five minutes.\"",
    "We waited; we hoped; we prepared for the worst.",
    "Honestly? I'm not sure — maybe yes, maybe no.",
    "She had it all: the house, the car, the title — everything.",
    "Click, click, click — the meter kept on ticking.",
    "He paused at the threshold; then, finally, he knocked.",
    "Three things mattered now: speed, silence, and luck.",
    "It wasn't a question — it was a command, plain and simple.",
    "The kids — bless them — had drawn on every wall.",
    "Wait for it... wait for it... there it goes!",
    "She said yes; he said no; the room went quiet.",
    "We packed light: one bag, one map, one chance.",
    "And the moral — if there is one — is to never assume.",
    "He whispered, \"Not yet,\" and raised a single finger.",
    "It dripped, slowly, steadily — drip, drip, drip — all night.",
    "First impressions matter; second chances, even more.",
    "The deadline — yesterday, technically — had long since passed.",
    "Ready or not — and clearly not — here it comes.",
    "She counted the cost; then, without a word, she paid it.",
    "It's late; I'm tired; let's pick this up tomorrow.",
    "He had everything to lose — and lose it he did.",
    "Quietly, almost shyly, the door creaked open.",
    "There's good news, bad news, and then there's this.",
    "We turned the corner — and there it was, at last.",
    "Stop, look, listen: the oldest rule there is.",
    "She smiled, shrugged, and walked right out the door.",
    "It was — how do I put this — a complete disaster.",
    "One step, then another; that's all it ever takes.",
    "The lights dimmed; the crowd hushed; the show began.",
    "He asked twice — politely, then not — and got no answer.",
    "Maybe tomorrow; maybe never; who's to say?",
    "And so it ended — quietly, without ceremony — the way it began.",
]

# ── poetry & rhythm (monotonic regression ft 0.18 → DPO 0.46) ──
POETRY = [
    "The moon hung low above the silver sea.",
    "And miles to go before I sleep, and miles to go.",
    "Twinkle, twinkle, little star, how I wonder what you are.",
    "The woods are lovely, dark and deep tonight.",
    "Two roads diverged inside a yellow wood.",
    "Shall I compare thee to a summer's day?",
    "The fog comes in on little cat feet.",
    "Roses are red, violets are blue, and morning light is breaking through.",
    "Hope is the thing with feathers that perches in the soul.",
    "I wandered lonely as a cloud above the hills.",
    "Tyger, tyger, burning bright in the forests of the night.",
    "Water, water, everywhere, and not a drop to drink.",
    "The rain it raineth every day, on hill and field and bay.",
    "Once upon a midnight dreary, while I pondered weak and weary.",
    "Do not go gentle into that good night.",
    "The sea is calm tonight, the tide is full, the moon lies fair.",
    "Season of mists and mellow fruitfulness, close friend of the sun.",
    "I think that I shall never see a poem lovely as a tree.",
    "Gather ye rosebuds while ye may, old time is still a-flying.",
    "The curfew tolls the knell of parting day.",
    "Bright star, would I were steadfast as thou art.",
    "A thing of beauty is a joy forever, never fading.",
    "The world is too much with us, late and soon.",
    "Western wind, when wilt thou blow, the small rain down can rain.",
    "My heart leaps up when I behold a rainbow in the sky.",
    "Tell me not, in mournful numbers, life is but an empty dream.",
    "How do I love thee? Let me count the ways.",
    "The owl and the pussycat went to sea in a beautiful pea-green boat.",
    "Half a league, half a league, half a league onward.",
    "When I have fears that I may cease to be.",
    "The splendor falls on castle walls and snowy summits old in story.",
    "Come live with me and be my love, and we will all the pleasures prove.",
    "Glory be to God for dappled things, for skies of couple-color.",
    "Earth has not anything to show more fair.",
    "Music, when soft voices die, vibrates in the memory.",
    "The night has a thousand eyes, and the day but one.",
    "Little lamb, who made thee? Dost thou know who made thee?",
    "She walks in beauty, like the night of cloudless climes and starry skies.",
    "Stay, stay at home, my heart, and rest; home-keeping hearts are happiest.",
    "Out of the cradle endlessly rocking, the singer sways and sings.",
    "April is the cruelest month, breeding lilacs out of the dead land.",
    "I have measured out my life with coffee spoons.",
    "Because I could not stop for Death, he kindly stopped for me.",
    "And the silken sad uncertain rustling of each purple curtain.",
    "Whose woods these are I think I know, his house is in the village though.",
    "Let us go then, you and I, when the evening is spread out against the sky.",
    "The yellow fog that rubs its back upon the windowpanes.",
    "Ah, love, let us be true to one another!",
    "In the room the women come and go, talking of Michelangelo.",
    "Til human voices wake us, and we drown.",
    "Wild nights, wild nights, were I with thee, wild nights should be our luxury.",
    "The heart asks pleasure first, and then, excuse from pain.",
    "A narrow fellow in the grass occasionally rides.",
    "Success is counted sweetest by those who ne'er succeed.",
    "Doubt thou the stars are fire; doubt that the sun doth move.",
    "To be, or not to be, that is the question.",
    "The quality of mercy is not strained, it droppeth as the gentle rain.",
    "Now is the winter of our discontent made glorious summer.",
    "Full fathom five thy father lies, of his bones are coral made.",
    "When forty winters shall besiege thy brow.",
    "Let me not to the marriage of true minds admit impediments.",
    "Death, be not proud, though some have called thee mighty.",
    "Batter my heart, three-personed God, for you as yet but knock.",
    "No man is an island, entire of itself.",
    "Had we but world enough, and time, this coyness would be no crime.",
    "They flee from me that sometime did me seek.",
    "Drink to me only with thine eyes, and I will pledge with mine.",
    "Go, lovely rose, tell her that wastes her time and me.",
    "Gather the flowers, but spare the buds.",
    "The world is charged with the grandeur of God.",
    "Margaret, are you grieving over goldengrove unleaving?",
    "I caught this morning morning's minion, kingdom of daylight's dauphin.",
    "Pied beauty: glory be to God for all things counter, original, spare.",
    "What happens to a dream deferred? Does it dry up like a raisin in the sun?",
    "I, too, sing America; I am the darker brother.",
    "Hold fast to dreams, for if dreams die, life is a broken-winged bird.",
    "Do I dare disturb the universe? In a minute there is time.",
    "We wear the mask that grins and lies, it hides our cheeks.",
]


def build_url_examples(n: int, rng: random.Random, cap: int = 110):
    out = []
    for _ in range(n):
        tpl = rng.choice(URL_TEMPLATES)
        out.append(tpl.format(name=rng.choice(_NAMES), dom=rng.choice(_DOMAINS),
                              path=rng.choice(_PATHS)))
    # dedup while preserving order, then cap to keep category balance
    seen, uniq = set(), []
    for t in out:
        if t not in seen:
            seen.add(t); uniq.append(t)
    return uniq[:cap]


def main():
    rng = random.Random(SEED)
    buckets = {
        "casual_speech": CASUAL,
        "urls_emails_paths": build_url_examples(300, rng),
        "emotional_speech": EMOTIONAL,
        "dialogue_attribution": DIALOGUE,
        "punctuation_pauses": PUNCTUATION,
        "poetry_rhythm": POETRY,
    }

    existing = [json.loads(l) for l in open(V1)]
    next_id = max(r["id"] for r in existing) + 1

    new_recs = []
    for cat, texts in buckets.items():
        for t in texts:
            new_recs.append({
                "id": next_id,
                "uuid": str(uuid.UUID(int=rng.getrandbits(128), version=4)),
                "text": t,
                "category": cat,
                "lang": "en",
                "source": "regression_anchor",
            })
            next_id += 1

    with open(V2, "w", encoding="utf-8") as f:
        for r in existing + new_recs:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")

    from collections import Counter
    print(f"v1: {len(existing)}  +new: {len(new_recs)}  → v2: {len(existing)+len(new_recs)}  → {V2}")
    print("new by category:", dict(Counter(r["category"] for r in new_recs)))


if __name__ == "__main__":
    main()
